name: Master Modeling Workshop
favicon: null
layout_spectrum: 0.761502628447488
typography_spectrum: 0.6838993525598198
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9071269382257015
  lightness: 0.5572553367819637
  saturation: 0.48466807696968317
  rhythmicContrast: 0.6617608014494181
purpose: []
